<#import "parts/common.ftlh" as c>

<@c.page>
    <h3>Hello, guest!</h3>
    <div>
        <p>
        <h4>- - - This is a ReqSystem application! - - -</h4>
        </p>
        <h5>To login/register/logout -> press button Sign In/Up/Out in the right top blue Button</h5>
        <h5>To go to main page (now you are at it) -> press <b>ReqSystem</b> in the let top black button</h5>
        <h5>Main functionality is available after sign-in procedure</h5>
    </div>
</@c.page>
